version: '3.8'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile    
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123!